### ISSUE TITLE
New error 1.0.4-alpha

### ISSUE THREAD

**Issue by BrutalCSEjziponken** [LordFetznschaedl/CS2Retake#22]
18:26:58 [WARN] (plugin:CS2Retake) No planted bomb entities have been found! This might be because no bomb was planted.
18:26:58 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at CS2Retake.Managers.RetakeManager.HasBombBeenPlantedCallback()
   at InvokeStub_Action.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82

**Comment by LordFetznschaedl** [comment]
Hello @BrutalCSEjziponken , 

I am sorry that it took me a few days. I have just released a new version that has this bug and many others fixed. Stability should be way higher now.

Could you please update to the newest version and give me a bit of feedback. Very thankful for that.

Regards
Robert
