### ISSUE TITLE
[EROR] (cssharp:Core) Error invoking callback

### ISSUE THREAD

**Issue by BrutalCSEjziponken** [LordFetznschaedl/CS2Retake#8]
New error in console:

11:24:03 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentOutOfRangeException: Non-negative number required. (Parameter 'maxValue')
   at System.Random.ThrowMaxValueMustBeNonNegative()
   at CS2Retake.Entities.MapEntity.GetRandomSpawn(CsTeam team, BombSiteEnum bombSite, Boolean hasToBeInBombZone)
   at CS2Retake.Managers.MapManager.TeleportPlayerToSpawn(CCSPlayerController player, Nullable`1 spawnIndex)
   at CS2Retake.CS2Retake.OnPlayerSpawn(EventPlayerSpawn event, GameEventInfo info)
   at InvokeStub_GameEventHandler`1.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82

**Comment by LordFetznschaedl** [comment]
Hi,
So you know what you did when this error occurred?
Thank you.

**Comment by BrutalCSEjziponken** [comment]
Not really. But Im kinda dumb also. I was running casual and skirmish 12 lol, forgot to change that when I added this plugin.. Lets just see if it happens again.. Also Svampkant is my admin (he created the other issue which is probably also solved now). :)

**Comment by LordFetznschaedl** [comment]
No problem. I will try and find out as much as possible using the error provided. Sadly I am only able to verify changes I do earliest on Sunday due to me being an a personal trip.

**Comment by LordFetznschaedl** [comment]
This should now be fixed with Release v1.0.2-alpha
